puts "Loading ThecoreBackendCommons seeds"
Thecore::Seed.save_setting :main, :app_name, "The Core by Gabriele Tassoni"

puts "Loading ThecoreBackendCommons SMTP config"
Thecore::Seed.save_setting :smtp, :delivery_method, ""
Thecore::Seed.save_setting :smtp, :from, ""
Thecore::Seed.save_setting :smtp, :address, ""
Thecore::Seed.save_setting :smtp, :port, ""
Thecore::Seed.save_setting :smtp, :domain, ""
Thecore::Seed.save_setting :smtp, :user_name, ""
Thecore::Seed.save_setting :smtp, :password, ""
Thecore::Seed.save_setting :smtp, :authentication, ""
Thecore::Seed.save_setting :smtp, :enable_starttls_auto, ""